### ISSUE TITLE
Bump fails on expect

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [zopencommunity/expectport#4]
Details here: https://github.com/ZOSOpenTools/expectport/actions/runs/6755634742/job/18364261073

**Comment by IgorTodorovskiIBM** [comment]
buildenv:1: 'https://sourceforge.net/projects/expect/files/Expect/|re:/latest(.*)expect([\d.]+).tar.gz/$2/|semver:*': no filter matches

FYI @v1gnesh

**Comment by v1gnesh** [comment]
Yup, Sourceforge links took the most digging.
Today I saw the big latest release button point to a 2 year old release for Tcl.
Will apply the same lookup technique for this (and other sourceforge links if any).

**Comment by IgorTodorovskiIBM** [comment]
Still seems to be an issue:
```
buildenv:1: 'https://sourceforge.net/projects/expect/files/Expect/|re:/Click.to.enter.([\d.]+)"/$1/|semver:*': no filter matches
```
